config/routes.rb
Pols::Application.routes.draw do

  devise_for :users
  resources :categories
  resources :home

  match 'victory_comments' => 'victories#new', :via => :post
  match 'victories' => 'victories#new', :as => 'victories', :via => :get
  match 'victories' => 'victories#create', :as => 'victories', :via => :post

  match 'victories/:id' => 'victories#show', :via => :get

  match 'help' => 'sites#help'

  match 'aboutus' => 'sites#aboutus'

  get "passwords/edit"

  get "users/profile"

  get "users/show"

  get "users/myaccount"

  devise_for :users,
             :controllers => { :registrations => "registrations" },
             :path => "users",
             :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  devise_for :users do
    resources :profiles
  end

  devise_for :users, :controllers => { :invitations => 'users/invitations' }

  resources :comments

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  enable_as_typus_user

  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_nested_set
  attr_accessible :name, :parent_id#, :lft, :rgt
  # attr_accessible :title, :body
  has_many :victories
  def path_name
    "#{'-' * self.level} #{self.name}"
  end
end

app/models/cms.rb
class Cms < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates_presence_of :body
  validates_presence_of :user

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user
  belongs_to :victory
  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    c = self.new
    c.commentable_id = obj.id
    c.commentable_type = obj.class.base_class.name
    logger.info("===============================#{comment.inspect}")
    c.body = comment[:body]
    c.title = comment[:title]
    c.subject = comment[:subject]
    c.user_id = user_id
    c
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.size > 0
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # attr_accessible :title, :body

  attr_accessible :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => {:with => %r{.+@.+\..+}}, :allow_blank => true


end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  attr_accessible :user_id, :first_name, :last_name, :address1, :address2, :city, :state, :zip, :phone, :website, :avatar

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "150x150>", :small =>"50x50" }

  def self.profile_create(id)
    return Profile.find_or_create_by_user_id(:user_id => id).id
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :invitable, :invite_for => 2.weeks

  has_one :profile
  accepts_nested_attributes_for :profile
  has_many :victories
  # Setup accessible (or protected) attributes for your model
  attr_accessor :password_confirmation
  attr_accessible :email, :password, :password_confirmation, :remember_me, :reset_password_token, :profile_attributes

  # attr_accessible :title, :body
end

app/models/victory.rb
class Victory < ActiveRecord::Base
  acts_as_commentable
  acts_as_taggable_on :tags
  # attr_accessible :title, :body
  belongs_to :category
  has_many :comments, :foreign_key => :commentable_id
  belongs_to :user
  attr_accessible :user_id, :title, :problem, :solution
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @victory = Victory.all
    @victory = Victory.paginate(:page => params[:page], :per_page => 10)
    if user_signed_in?
      user = current_user.id
      myvictory(user)
    end
  end

  def myvictory(user)
    @myvictory = Victory.find(:all, :conditions => ["user_id=#{user}"])
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def help
    @help = Cms.find_by_id(2)
  end

  def aboutus
    @about = Cms.find_by_id(1)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :should_be_user, :only => [:myaccount, :profile]

  def show
  end

  def myaccount
    @user = current_user
    @profile = current_user.profile
  end

  def update
    @user = current_user
    @profile = current_user.profile
    if params[:redirect_from] == "myaccount"
      if @user.valid_password?(params[:password])
        @user.password = params[:new_password]
        @user.save(:validate => false)
        sign_in(@user, :bypass => true)
        redirect_to user_myaccount_path(@user), :notice => "Password Updated"
      else
        redirect_to user_myaccount_path(@user), :notice => "Old Password Not Match"
      end
    end
  end

  def profile
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/victories_helper.rb
module VictoriesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Project On Live</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%#= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "bootstrap.min", "bootstrap-responsive", "docs", "custom" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to image_tag("logo.png", :border => 0), root_path, {:class => "brand"} %>
      <div class="nav-collapse">
        <ul class="nav">
          <li <%= ('class=active' if controller_name == 'home' && action_name == "index") %>><%= link_to "Home", root_path %></li>
          <% if user_signed_in? %>
              <li <%= ('class=active' if controller_name == 'victories' && action_name == "new") %>><%= link_to "Add Victory", victories_path %></li>
          <% end %>
          <li <%= ('class=active' if controller_name == 'sites' && action_name == "aboutus") %>><%= link_to "About Us", aboutus_path %></li>
          <li <%= ('class=active' if controller_name == 'contact' && action_name == "new") %>><%= link_to "Contact Us", contact_path %></li>
          <li <%= ('class=active' if controller_name == 'sites' && action_name == "help") %>><%= link_to "Help", help_path %></li>
        </ul>
        <ul class="nav pull-right">
          <% if user_signed_in? %>
              <li class="middle">Signed in as <%= current_user.email %>. This cannot be cheese?</li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.profile.first_name %>
                  <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "My Account", "/users/myaccount" %></li>
                  <li><%= link_to "View Profile", "/users/profile" %></li>
                  <li><%= link_to "Edit Profile", "/users/edit" %></li>
                  <li><%= link_to "Invite User", new_user_invitation_path %></li>
                  <li class="divider"></li>
                  <li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                </ul>
              </li>
          <% else %>
              <li <%= ('class=active' if controller_name == 'registrations' && action_name == "new") %>>
                <%= link_to 'Register', new_user_registration_path %>
              </li>
              <li <%= ('class=active' if controller_name == 'sessions' && action_name == "new") %>>
                <%= link_to 'Sign in', new_user_session_path %>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do %>
          <a class="close" data-dismiss="alert" href="#">×</a>
          <%= msg %>
      <% end %>
  <% end %>
  <%= yield %>
  <hr>
  <footer>
    <p>&copy; Company 2012</p>
  </footer>
</div>
</body>
</html>